spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: NtT.1996
    #url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh
    #url: jdbc:mysql://localhost:3306/hrm?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&useSSL=false&allowPublicKeyRetrieval=true
    url: jdbc:mysql://localhost:3306/hrm
  rabbitmq:
    username: hrm
    password: NtT.1996
    host: 127.0.0.1
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password: NtT.1996
  cache:
    cache-names: menus_cache
server:
  port: 8081
  compression:
    enabled: true
fastdfs:
  nginx:
    host: http://192.168.91.128/
