version: "3.8"
services:
  mysql:
    image: mysql:8.0.22
    # container_name: mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - hrm_net
    environment:
      MYSQL_DATABASE: hrm
      MYSQL_USER: hrm
      MYSQL_PASSWORD: NtT.1996
      MYSQL_ROOT_PASSWORD: NtT.1996

  rabbitmq:
    # https://stackoverflow.com/questions/30747469/how-to-add-initial-users-when-starting-a-rabbitmq-docker-container
    # image: rabbitmq:3.8.9-management-alpine
    build: ./rabbitmq
    container_name: hrm_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: hrm
      RABBITMQ_DEFAULT_PASS: NtT.1996
      RABBITMQ_DEFAULT_VHOST: hrm_net
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    networks:
      - hrm_net
    restart: always
    ports:
      - "5672:5672"
      - "15672:5672"

#  redis:
#    image: redis:6.0.9-alpine
#    expose:
#      - "6379"
#    networks:
#      - nestjs_example_network
#    container_name: nestjs_example-redis
#    restart: always

volumes:
  hrm_mysql:
  hrm_rabbitmq:

networks:
  hrm_net:
    driver: bridge
